services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 5500
      PORT_GRPC: 50052
      MONGO_STRING_CONNECTION: mongodb://mongo:27017
      MONGO_DB_NAME: micro_template
      REDIS_SERVER_URI: redis://redis:6379
      REDIS_DB: 1
      JWT_SECRET: dev-jwt-secret-key
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: micro-template
      KAFKA_GROUP_ID: micro-template-group
      GRPC_URL_USER: localhost:50052
    volumes:
      - ./src:/app/src
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json

  mongo:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"

  kafka:
    ports:
      - "9092:9092"
