FROM node:22-alpine

RUN apk add --no-cache python3 make g++ libc6-compat && rm -rf /var/cache/apk/*
RUN npm install -g pnpm@10.10.0

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5500 50052

CMD ["pnpm", "start:dev"]
